# Generated by Django 3.1.1 on 2020-10-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_title', models.CharField(max_length=100)),
                ('sample_artist', models.CharField(default='', max_length=100)),
                ('sample_address', models.CharField(max_length=100)),
                ('sample_time_stamp', models.CharField(max_length=10)),
                ('sample_views', models.IntegerField(default=0)),
                ('sample_likes', models.IntegerField(default=0)),
                ('og_title', models.CharField(max_length=100)),
                ('og_artist', models.CharField(default='', max_length=100)),
                ('og_address', models.CharField(max_length=100)),
                ('og_time_stamp', models.CharField(max_length=10)),
                ('og_views', models.IntegerField(default=0)),
                ('og_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
