# Generated by Django 3.1.1 on 2020-10-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('song_artist', models.CharField(default='', max_length=100)),
                ('song_videoId', models.CharField(max_length=100)),
                ('song_time_stamp', models.CharField(max_length=10)),
                ('song_views', models.IntegerField(default=0)),
                ('song_likes', models.IntegerField(default=0)),
                ('sampled_title', models.CharField(max_length=100)),
                ('sampled_artist', models.CharField(default='', max_length=100)),
                ('sampled_videoId', models.CharField(max_length=100)),
                ('sampled_time_stamp', models.CharField(max_length=10)),
                ('sampled_views', models.IntegerField(default=0)),
                ('sampled_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
